// ⚠️ FICHIER AUTO-GÉNÉRÉ — ne pas modifier manuellement
// Modifie CLIENT.md puis relance : npm run sync-client

export const clientConfig = {
  identity: {
    prenomDirigeant: "Jean Eddy",
    nomDirigeant: "Olivar",
    nomEntreprise: "Atom Plomberie Charpente Menuiserie",
    nomLegal: "ATOM PLOMBERIE CHARPENTE MENUISERIE",
    genreDirigeant: "masculin",
    founder: "Jean Eddy Olivar",
  },
  contact: {
    telephone: "06 92 79 98 92",
    telephoneHref: "tel:+262692799892",
    telephoneUrgence: "06 92 79 98 92",
    email: "bonkoinplombier@gmail.com",
    adresse: "160 Chemin Stéphane",
    ville: "Le Tampon",
    codePostal: "97430",
    departement: "La Réunion",
    region: "La Réunion",
    zoneIntervention: "Le Tampon et 30km autour",
    zoneKm: "30",
  },
  horaires: {
    semaine: "7h00 - 17h00",
    samedi: "7h00 - 12h00",
    dimanche: "Fermé",
    urgence: "24h/24 7j/7",
  },
  branding: {
    couleurPrimaireHue: "245",
    couleurAccentHue: "44",
  },
  social: {
    facebook: "",
    instagram: "",
    google: "",
  },
  domaine: "atom-plomberie.re",
  url: "https://atom-plomberie.re",
  legal: {
    siret: "991 648 726 00016",
    rge: "",
    assuranceDecennale: "",
  },
  chiffres: {
    anneesExperience: 4,
    nombreInterventions: 500,
    noteGoogle: 4.8,
    nombreAvis: 30,
    anneeCreation: 2022,
    delaiIntervention: "2h",
    disponibilite: "7j/7",
    tauxSatisfaction: "98",
  },
  geo: {
    latitude: "-21.2781",
    longitude: "55.5156",
  },
  communes: [
    { name: "Le Tampon", postalCode: "97430" },
    { name: "Saint-Pierre", postalCode: "97410" },
    { name: "Saint-Louis", postalCode: "97450" },
    { name: "L'Entre-Deux", postalCode: "97414" },
    { name: "Petite-Île", postalCode: "97429" },
    { name: "Saint-Joseph", postalCode: "97480" },
    { name: "Les Avirons", postalCode: "97425" },
    { name: "Étang-Salé", postalCode: "97427" },
    { name: "Cilaos", postalCode: "97413" },
    { name: "La Plaine des Cafres", postalCode: "97418" },
  ],
  services: [
    { title: "Dépannage urgent", shortDescription: "Intervention rapide pour toutes vos urgences plomberie à La Réunion.", description: "Fuite d'eau, canalisation bouchée, dégât des eaux... Notre équipe intervient en urgence 7j/7 dans le sud de La Réunion. Diagnostic sur place et réparation immédiate dans la majorité des cas.", icon: "Siren", slug: "/depannage-plomberie" },
    { title: "Plomberie générale", shortDescription: "Installation, remplacement et mise aux normes de vos équipements.", description: "Robinetterie, tuyauterie, raccordements, WC, éviers, recherche de fuite... Nous intervenons pour tous vos travaux de plomberie, de l'installation neuve à la mise aux normes de vos installations existantes.", icon: "Wrench", slug: "/plomberie" },
    { title: "Salle de bain", shortDescription: "Rénovation complète, douche italienne, adaptation PMR.", description: "De la conception à la réalisation, nous prenons en charge votre projet de rénovation de salle de bain. Douche italienne, remplacement baignoire, accessibilité PMR, meuble vasque... Un interlocuteur unique du début à la fin.", icon: "Bath", slug: "/renovation-salle-de-bain" },
    { title: "Charpente", shortDescription: "Construction, rénovation et traitement de charpente bois.", description: "Réalisation de charpentes traditionnelles et industrielles, rénovation de toiture, traitement anti-termites et fongicide, pose de couverture. Intervention sur maisons individuelles et bâtiments à La Réunion.", icon: "Hammer", slug: "/charpente" },
    { title: "Menuiserie", shortDescription: "Portes, fenêtres, escaliers et aménagements bois sur mesure.", description: "Fabrication et pose de menuiseries intérieures et extérieures : portes, fenêtres, volets, escaliers, placards, terrasses bois. Travail artisanal et matériaux adaptés au climat tropical.", icon: "DoorOpen", slug: "/menuiserie" },
    { title: "Chauffe-eau", shortDescription: "Installation, remplacement et entretien de chauffe-eau.", description: "Remplacement de chauffe-eau électrique, installation de chauffe-eau solaire ou thermodynamique pour réduire votre facture énergétique. Détartrage et entretien pour prolonger la durée de vie de votre équipement.", icon: "Droplets", slug: "/chauffe-eau" },
  ],
  testimonials: [
    { name: "Marie-Line P.", rating: 5, text: "Intervention très rapide pour une fuite dans ma cuisine. Travail propre et soigné, je recommande vivement Atom Plomberie !", date: "2025-10-15", source: "Google" },
    { name: "Thierry R.", rating: 5, text: "Excellente prestation pour la rénovation complète de ma salle de bain. Jean Eddy est à l'écoute et de bon conseil.", date: "2025-09-22", source: "Google" },
    { name: "Nathalie B.", rating: 5, text: "Très satisfaite de la pose de ma charpente. Équipe sérieuse et respectueuse des délais. Merci !", date: "2025-08-10", source: "Google" },
    { name: "David M.", rating: 4, text: "Bon travail pour le remplacement de mon chauffe-eau solaire. Un peu d'attente pour le rendez-vous mais résultat impeccable.", date: "2025-07-18", source: "Google" },
    { name: "Sophie L.", rating: 5, text: "Menuiserie sur mesure pour mes placards et ma terrasse bois. Résultat magnifique, finitions parfaites.", date: "2025-11-05", source: "Google" },
    { name: "Patrick H.", rating: 5, text: "Dépannage un dimanche matin pour une canalisation bouchée. Rapide, efficace et tarif honnête.", date: "2025-06-30", source: "Google" },
    { name: "Françoise D.", rating: 5, text: "Rénovation de la charpente de ma case créole. Travail remarquable, respect du bâti ancien. Bravo !", date: "2025-05-12", source: "Google" },
    { name: "Jean-Marc V.", rating: 4, text: "Installation de fenêtres en bois pour toute la maison. Bonne qualité, pose soignée. Petit retard de livraison.", date: "2025-04-25", source: "Google" },
    { name: "Claudine G.", rating: 5, text: "Atom Plomberie a refait toute ma tuyauterie. Travail impeccable et propre. Je recommande à 100%.", date: "2025-03-15", source: "Google" },
    { name: "Bruno T.", rating: 5, text: "Super travail pour la construction de mon escalier bois et la terrasse. Artisan passionné et compétent.", date: "2025-02-20", source: "Google" },
  ],
  admin: {
    password: "1234",
  },
  seo: {
    metaTitleAccueil: "Plombier Le Tampon — Atom Plomberie Charpente Menuiserie | Dépannage 7j/7",
    metaDescAccueil: "Plombier, charpentier et menuisier au Tampon (La Réunion). Dépannage urgent 7j/7, installation, rénovation salle de bain, charpente bois, menuiserie sur mesure. Devis gratuit.",
    descriptionEntreprise: "Plombier, charpentier et menuisier au Tampon (La Réunion). Dépannage urgent 7j/7, installation, rénovation salle de bain, charpente bois, menuiserie sur mesure. Devis gratuit.",
    slogan: "Votre artisan au Tampon — Plomberie, Charpente & Menuiserie",
  },
} as const;

export type ClientConfig = typeof clientConfig;
